pod 'JSONKit', :podspec => "https://bitbucket.org/gprandrpg/adfurikunsdk/raw/c27f7cc7e50764595ef6fe2f8f25859a9f727ad7/JSONKit.podspec"
pod 'AdfurikunSDK', :podspec => 'https://bitbucket.org/gprandrpg/adfurikunsdk/raw/c27f7cc7e50764595ef6fe2f8f25859a9f727ad7/AdfurikunSDK.podspec'

